"""
Auto-generated patch for DatabaseConnectionError
========================================
Error ID   : sim_1_1776075382
Cluster    : CLU_0000
Root Cause : Automated analysis unavailable: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. 
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-2.0-flash
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-2.0-flash
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-2.0-flash
Please retry in 29.771772449s. [links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_input_token_count"
  quota_id: "GenerateContentInputTokensPerModelPerMinute-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
}
violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
}
violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
}
, retry_delay {
  seconds: 29
}
]
Confidence : 92%
Generated  : 2026-04-13 10:16:30 UTC

IMPORTANT: This patch was generated by AI.
Review carefully before merging into production.
"""

# ── Affected File ──────────────────────────────────────────────────────────
# File : db/database.ts
# Line : 88
# ──────────────────────────────────────────────────────────────────────────

import time

def acquire_connection(pool, max_retries=3):
    for attempt in range(max_retries):
        try:
            return pool.acquire(timeout=30)
        except PoolExhaustedError:
            if attempt < max_retries - 1:
                wait = 2 ** attempt   # exponential backoff
                time.sleep(wait)
            else:
                raise


# ── References ────────────────────────────────────────────────────────────
# # https://stackoverflow.com/q/db-pool-exhausted
# https://www.postgresql.org/docs/current/runtime-config-connection.html
